#!/bin/bash
# deploy-ui.sh — Upload built UI to S3 and invalidate CloudFront cache
#
# Generates config.js with real API Gateway URL and Cognito settings
# from CloudFormation stack outputs, so no env vars needed at build time.
#
# Usage:
#   cd sam
#   ./deploy-ui.sh [stack-name] [region] [ui-out-dir] [--profile profile-name]
#
# Example:
#   ./deploy-ui.sh polyris-dev us-east-1
#   ./deploy-ui.sh polyris-dev us-east-1 ../ui/out --profile my-profile

set -e

STACK_NAME="${1:-polyris-dev}"
REGION="${2:-us-east-1}"
UI_OUT_DIR="${3:-../ui/out}"

# Parse --profile flag (can be anywhere in args)
AWS_PROFILE_FLAG=""
for arg in "$@"; do
  if [ "$prev" = "--profile" ]; then
    AWS_PROFILE_FLAG="--profile $arg"
  fi
  prev="$arg"
done

if [ ! -d "$UI_OUT_DIR" ]; then
  echo "Error: UI build not found at $UI_OUT_DIR"
  echo "Run: cd ../ui && npm ci && npm run build"
  exit 1
fi

echo "Fetching stack outputs for: $STACK_NAME"

get_output() {
  aws cloudformation describe-stacks $AWS_PROFILE_FLAG \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

UI_BUCKET=$(get_output "ConsoleUiBucket")
DIST_ID=$(get_output "ConsoleUiDistributionId")
CONSOLE_URL=$(get_output "ConsoleUiUrl")
API_URL=$(get_output "ConsoleApiUrl")/api
COGNITO_POOL_ID=$(get_output "CognitoUserPoolId")
COGNITO_CLIENT_ID=$(get_output "CognitoClientId")

if [ -z "$UI_BUCKET" ]; then
  echo "Error: ConsoleUiBucket not found in stack $STACK_NAME"
  exit 1
fi

# Generate config.js with real values — loaded at runtime in browser
echo "Generating config.js with stack outputs..."
AUTH_ENABLED="false"
if [ -n "$COGNITO_POOL_ID" ] && [ "$COGNITO_POOL_ID" != "None" ]; then
  AUTH_ENABLED="true"
fi

cat > "$UI_OUT_DIR/config.js" << ENDOFCONFIG
// Polyris Console Configuration
// Auto-generated by deploy-ui.sh — do not edit manually
window.CONFIG = {
    API_URL: '$API_URL',
    POLL_INTERVAL: 30000,
    AUTH: {
        enabled: $AUTH_ENABLED,
        userPoolId: '$COGNITO_POOL_ID',
        clientId: '$COGNITO_CLIENT_ID',
        region: '$REGION'
    }
};
ENDOFCONFIG

echo "Uploading UI to s3://$UI_BUCKET"

# Assets (_next/static) — immutable cache (content-hashed filenames)
aws s3 sync "$UI_OUT_DIR" "s3://$UI_BUCKET" $AWS_PROFILE_FLAG \
  --delete \
  --exclude "*.html" \
  --exclude "config.js" \
  --cache-control "public, max-age=31536000, immutable"

# HTML files — no cache (always fresh)
aws s3 sync "$UI_OUT_DIR" "s3://$UI_BUCKET" $AWS_PROFILE_FLAG \
  --delete \
  --exclude "*" \
  --include "*.html" \
  --cache-control "public, max-age=0, must-revalidate"

# config.js — no cache (contains runtime config)
aws s3 cp "$UI_OUT_DIR/config.js" "s3://$UI_BUCKET/config.js" $AWS_PROFILE_FLAG \
  --cache-control "public, max-age=0, must-revalidate"

echo "Invalidating CloudFront cache: $DIST_ID"
aws cloudfront create-invalidation $AWS_PROFILE_FLAG \
  --distribution-id "$DIST_ID" \
  --paths "/*" \
  --region us-east-1 \
  --output text > /dev/null

echo ""
echo "✅ UI deployed successfully!"
echo "   URL: $CONSOLE_URL"
echo "   API: $API_URL"
