"""
UI Bootstrap — CloudFormation Custom Resource

Copies pre-built UI from the public Polyris releases bucket
into the customer's private S3 bucket on stack create/update.

Triggered by CloudFormation as a Custom Resource.
"""
import boto3
import cfnresponse

s3 = boto3.client('s3')


def handler(event, context):
    try:
        props = event['ResourceProperties']
        dest_bucket = props['DestBucket']
        source_bucket = props['SourceBucket']
        source_prefix = props['SourcePrefix']  # e.g. v1.0.0/ui
        api_url = props.get('ApiUrl', '')
        cognito_pool_id = props.get('CognitoUserPoolId', '')
        cognito_client_id = props.get('CognitoClientId', '')
        region = props.get('Region', 'us-east-1')

        request_type = event['RequestType']

        if request_type == 'Delete':
            # Empty the UI bucket on stack deletion
            paginator = s3.get_paginator('list_objects_v2')
            for page in paginator.paginate(Bucket=dest_bucket):
                objects = [{'Key': o['Key']} for o in page.get('Contents', [])]
                if objects:
                    s3.delete_objects(Bucket=dest_bucket, Delete={'Objects': objects})
            cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
            return

        # Create or Update — copy UI files from releases bucket
        paginator = s3.get_paginator('list_objects_v2')
        copied = 0

        for page in paginator.paginate(Bucket=source_bucket, Prefix=source_prefix + '/'):
            for obj in page.get('Contents', []):
                src_key = obj['Key']
                # Strip prefix: v1.0.0/ui/index.html → index.html
                dest_key = src_key[len(source_prefix) + 1:]
                if not dest_key:
                    continue

                # Set cache headers
                extra_args = {}
                if dest_key.endswith('.html') or dest_key == 'config.js':
                    extra_args['CacheControl'] = 'public, max-age=0, must-revalidate'
                else:
                    extra_args['CacheControl'] = 'public, max-age=31536000, immutable'

                s3.copy_object(
                    CopySource={'Bucket': source_bucket, 'Key': src_key},
                    Bucket=dest_bucket,
                    Key=dest_key,
                    **extra_args
                )
                copied += 1

        # Generate config.js with real API Gateway URL and Cognito settings
        auth_enabled = 'true' if cognito_pool_id else 'false'
        config_js = f"""// Polyris Console Configuration
// Auto-generated by CloudFormation — do not edit manually
window.CONFIG = {{
    API_URL: '{api_url}',
    POLL_INTERVAL: 30000,
    AUTH: {{
        enabled: {auth_enabled},
        userPoolId: '{cognito_pool_id}',
        clientId: '{cognito_client_id}',
        region: '{region}'
    }}
}};
"""
        s3.put_object(
            Bucket=dest_bucket,
            Key='config.js',
            Body=config_js.encode('utf-8'),
            ContentType='application/javascript',
            CacheControl='public, max-age=0, must-revalidate'
        )
        print(f"Copied {copied} files + generated config.js → s3://{dest_bucket}/")
        cfnresponse.send(event, context, cfnresponse.SUCCESS, {'FilesCopied': str(copied)})

    except Exception as e:
        print(f"Error: {e}")
        cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})
