"""
constants_generated.py — generated from polyris/constants.py by polyris.codegen.sync_enums.

DO NOT EDIT THIS FILE. Run `make generate-enums` (or
`python -m polyris.codegen.sync_enums`) to regenerate.

Canonical source sha (first 16): 5ce6d395a4552bf4
"""

class TaskStatus:
    """Task execution status values."""
    WAITING = 'waiting'
    DEPS_READY = 'deps_ready'
    WAITING_DELAY = 'waiting_delay'
    WAITING_PAUSED = 'waiting_paused'
    WAITING_DECISION = 'waiting_decision'
    RUNNING = 'running'
    PENDING = 'pending'
    SUCCESS = 'success'
    SUCCEEDED = 'succeeded'
    FAILED = 'failed'
    UPSTREAM_FAILED = 'upstream_failed'
    ABORTED = 'aborted'
    SKIPPED = 'skipped'
    STOPPED = 'stopped'

TASK_TERMINAL_STATUSES = {
    'aborted',
    'failed',
    'skipped',
    'succeeded',
    'success',
    'upstream_failed',
}
TASK_SETTLED_STATUSES = {
    'aborted',
    'failed',
    'skipped',
    'stopped',
    'succeeded',
    'success',
    'upstream_failed',
}
TASK_SUCCESS_STATUSES = {
    'skipped',
    'succeeded',
    'success',
}
TASK_FAILURE_STATUSES = {
    'aborted',
    'failed',
    'upstream_failed',
}
TASK_ACTIVE_STATUSES = {
    'pending',
    'running',
}
TASK_WAITING_STATUSES = {
    'deps_ready',
    'waiting',
    'waiting_decision',
    'waiting_delay',
    'waiting_paused',
}
TASK_STOPPABLE_STATUSES = {
    'deps_ready',
    'pending',
    'running',
    'waiting',
    'waiting_decision',
    'waiting_delay',
    'waiting_paused',
}

class TriggerRule:
    """Trigger rules."""
    ALL_SUCCESS = 'all_success'
    ONE_SUCCESS = 'one_success'
    ALL_DONE = 'all_done'
    ALL_SKIPPED = 'all_skipped'
    NONE_SKIPPED = 'none_skipped'

class PipelineStatus:
    """A pipeline card's status: its LAST run's canonical status, or 'idle' when the
    pipeline has no runs in the recent window (ADR #112, option c). The value set is
    ExecutionStatus plus 'idle' — kept in sync with ExecutionStatus."""
    RUNNING = 'running'
    SUCCESS = 'success'
    FAILED = 'failed'
    TIMED_OUT = 'timed_out'
    ABORTED = 'aborted'
    RECOVERED = 'recovered'
    IDLE = 'idle'

class ExecutionStatus:
    """Pipeline-execution status. Canonical lowercase form.

    AWS Step Functions returns these statuses in UPPERCASE; normalize at
    the boundary using `normalize_execution_status` before use. Canonical
    "success" (not "succeeded") system-wide per ADR #112 — supersedes ADR #71's
    value choice. `stopped` is a task-only status (restartable UI-stop) and is
    intentionally absent here: a stopped execution derives/reconciles to `aborted`.
    """
    RUNNING = 'running'
    SUCCESS = 'success'
    FAILED = 'failed'
    TIMED_OUT = 'timed_out'
    ABORTED = 'aborted'
    RECOVERED = 'recovered'

class BackfillStatus:
    """Backfill status — aggregate of N partition outcomes (ADR #54)."""
    PENDING = 'pending'
    RUNNING = 'running'
    COMPLETED = 'completed'
    FAILED = 'failed'
    PARTIAL = 'partial'
    CANCELED = 'canceled'

class BackfillCascade:
    """Asset backfill cascade mode — how downstream consumers are handled."""
    AUTO = 'auto'
    ALL = 'all'
    NONE = 'none'

class BackfillUpstream:
    """Asset backfill upstream lineage build mode (ADR #92).

    Mirrors BackfillCascade on the upstream side. Codegen-generated into
    constants_generated.py (backend) and ui/src/generated/enums.ts (UI) so the
    backend validator and the TS type derive from this one definition rather
    than hand-maintained copies (ADR #94)."""
    OFF = 'off'
    SMART = 'smart'
    FORCE = 'force'

class BackfillGranularity:
    """Backfill partition cadence (ADR #50)."""
    HOURLY = 'hourly'
    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'

class StalenessStatus:
    """Asset freshness vs declared SLA window."""
    FRESH = 'fresh'
    WARNING = 'warning'
    STALE = 'stale'
    UNKNOWN = 'unknown'

class AssetOperator:
    """How multiple asset dependencies combine to trigger downstream."""
    AND = 'AND'
    OR = 'OR'

EXECUTION_STATUS_CANONICAL = {
    'aborted',
    'failed',
    'recovered',
    'running',
    'success',
    'timed_out',
}
BACKFILL_TERMINAL_STATUSES = {
    'canceled',
    'completed',
    'failed',
    'partial',
}
BACKFILL_ACTIVE_STATUSES = {
    'pending',
    'running',
}
BACKFILL_ERROR_CODES = {
    'already_terminal',
    'child_name_too_long',
    'concurrent_backfill_active',
    'granularity_override_not_allowed',
    'id_space_exhausted',
    'internal_error',
    'invalid_downstream',
    'invalid_downstream_for_pipeline_target',
    'invalid_granularity_override',
    'invalid_options',
    'invalid_partition_format',
    'invalid_partition_keys',
    'invalid_partitions',
    'invalid_target',
    'invalid_target_type',
    'invalid_tasks',
    'invalid_upstream',
    'invalid_upstream_for_pipeline_target',
    'malformed_body',
    'malformed_parent',
    'misconfigured',
    'multi_producer_asset',
    'no_producer',
    'not_eligible',
    'not_found',
    'nothing_to_retry',
    'nothing_to_run',
    'partition_keys_not_failed',
    'producer_pipeline_missing',
    'range_too_large',
    'sfn_start_failed',
    'status_race',
    'target_not_found',
    'throttled',
    'unreachable_target_type',
    'upstream_cycle',
}

_EXECUTION_STATUS_UPPERCASE_MAP = {
    'RUNNING': 'running',
    'SUCCEEDED': 'success',
    'FAILED': 'failed',
    'TIMED_OUT': 'timed_out',
    'ABORTED': 'aborted',
    'STOPPED': 'aborted',
    'SUCCESS': 'success',
    'success': 'success',
    'succeeded': 'success',
}

def normalize_execution_status(status, log_warn=None):
    """Normalize a pipeline-execution status to canonical lowercase.

    Generated mirror of polyris.constants.normalize_execution_status.
    See ADR #71 for full reasoning. Idempotent on canonical inputs.
    """
    if status is None:
        return None
    if status in EXECUTION_STATUS_CANONICAL:
        return status
    mapped = _EXECUTION_STATUS_UPPERCASE_MAP.get(status)
    if mapped is not None:
        return mapped
    if log_warn is not None:
        log_warn("Unexpected execution status; cannot normalize",
                 status=status)
    return status

_DERIVE_RESOLVED = {'skipped', 'succeeded', 'success'}
_DERIVE_FAILURE = {'failed'}
_DERIVE_STOPPED = {'aborted', 'stopped', 'upstream_failed'}
_DERIVE_TERMINAL = {'aborted', 'failed', 'skipped', 'stopped', 'succeeded', 'success', 'upstream_failed'}

def derive_execution_status(task_statuses):
    """Derive a pipeline-execution status from its task statuses (DynamoDB only).

    The single source of this derivation (ADR #112). Returns one of the
    DynamoDB-derivable canonical values: 'running', 'success', 'failed', 'aborted'.
    ('timed_out' and 'recovered' are reconciliation-only — see
    ``reconcile_execution_status``.) A genuine task failure outranks an interruption;
    an interruption (stopped/aborted/upstream_failed) without a failure is 'aborted'.
    """
    statuses = set(task_statuses)
    if not statuses:
        return ExecutionStatus.RUNNING
    is_completed = statuses.issubset(_DERIVE_TERMINAL)
    has_failure = bool(statuses & _DERIVE_FAILURE)
    has_stopped = bool(statuses & _DERIVE_STOPPED)
    if is_completed:
        if has_stopped and not has_failure:
            return ExecutionStatus.ABORTED
        return ExecutionStatus.FAILED if has_failure else ExecutionStatus.SUCCESS
    if has_failure:
        return ExecutionStatus.FAILED
    if has_stopped:
        return ExecutionStatus.ABORTED
    return ExecutionStatus.RUNNING

def reconcile_execution_status(base, sfn_status, all_tasks_resolved):
    """Refine a derived 'running' status against the authoritative SFN status (ADR #112).

    Only a 'running' base is reconciled — terminal derivations are trusted. ``sfn_status``
    must already be canonical (see ``normalize_execution_status``). When SFN reports a
    failure/timeout but every task resolved, the execution is 'recovered'.
    """
    if base != ExecutionStatus.RUNNING:
        return base
    if not sfn_status or sfn_status == ExecutionStatus.RUNNING:
        return base
    if sfn_status in (ExecutionStatus.FAILED, ExecutionStatus.TIMED_OUT) and all_tasks_resolved:
        return ExecutionStatus.RECOVERED
    return sfn_status
