"""polyris-build-lambda — stamp XCom helpers into a Lambda handler directory.

Creates a minimal ``polyris/`` package containing only ``xcom.py`` inside the
target directory so Lambda functions can ``from polyris import xcom`` without
a pip install step in the zip build.

Generated package layout::

    <dest>/
      polyris/
        __init__.py   ← re-exports the xcom module
        xcom.py       ← verbatim copy of the installed polyris.xcom module

The generated files are a snapshot of the installed polyris version.
Re-run ``polyris-build-lambda <dir>`` after a polyris upgrade to refresh them.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import Optional


def _xcom_source() -> Path:
    """Resolve the path to the installed ``polyris/xcom.py``."""
    import polyris.xcom as _m
    src = Path(_m.__file__)
    if src.suffix != '.py' or not src.exists():  # pragma: no cover — compiled-only or corrupt wheel
        raise FileNotFoundError(
            f"Cannot locate polyris/xcom.py source at {src!r}. "
            "Ensure polyris is installed with source (not a compiled-only wheel)."
        )
    return src


# Minimal __init__.py written into the generated package.
# Only exposes `xcom` as a submodule — that is all Lambda tasks need.
_INIT_CONTENT = '''\
"""polyris — XCom helpers snapshot for Lambda.

Generated by ``polyris-build-lambda``. Contains only ``xcom.py``.
Re-run the command after a polyris upgrade to refresh this snapshot.

Usage::

    from polyris import xcom

    def handler(event, context):
        data = xcom.get(event, "upstream_task")
        return {"processed": len(data)}
"""
from . import xcom  # noqa: F401
'''


def stamp(dest_dir: Path, *, force: bool = False) -> Path:
    """Copy XCom helpers into ``dest_dir/polyris/``.

    Args:
        dest_dir: Lambda handler directory that will contain the generated
            ``polyris/`` package.
        force: Overwrite an existing ``polyris/`` directory. Default ``False``.

    Returns:
        Path of the generated ``polyris/`` package directory.

    Raises:
        FileNotFoundError: ``dest_dir`` does not exist.
        FileExistsError: ``dest_dir/polyris/`` already exists and ``force``
            is ``False``.
    """
    if not dest_dir.exists():
        raise FileNotFoundError(f"Directory not found: {dest_dir}")
    if not dest_dir.is_dir():
        raise NotADirectoryError(f"Not a directory: {dest_dir}")

    pkg_dir = dest_dir / "polyris"
    if pkg_dir.exists() and not force:
        raise FileExistsError(
            f"{pkg_dir} already exists. Pass --force to overwrite."
        )

    pkg_dir.mkdir(exist_ok=True)
    shutil.copy2(_xcom_source(), pkg_dir / "xcom.py")
    (pkg_dir / "__init__.py").write_text(_INIT_CONTENT, encoding="utf-8")
    return pkg_dir


def main(argv: Optional[list] = None) -> int:
    """CLI entry point for ``polyris-build-lambda``."""
    parser = argparse.ArgumentParser(
        prog="polyris-build-lambda",
        description=(
            "Stamp Polyris XCom helpers into a Lambda handler directory.\n\n"
            "Creates polyris/xcom.py + polyris/__init__.py inside <dir> so\n"
            "Lambda functions can 'from polyris import xcom' without a pip\n"
            "install step in the zip build."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "dir",
        metavar="<dir>",
        help="Lambda handler directory to stamp helpers into",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing polyris/ directory",
    )
    args = parser.parse_args(argv)

    dest = Path(args.dir)
    try:
        pkg_dir = stamp(dest, force=args.force)
    except (FileNotFoundError, FileExistsError, NotADirectoryError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    import polyris
    print(f"stamped polyris {polyris.__version__} helpers → {pkg_dir}")
    print("Lambda functions can now: from polyris import xcom")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
