"""
polyris init — Scaffold a new pipeline.

Usage:
    polyris-init my-pipeline
    polyris-init my-pipeline --local        # Try without AWS
    polyris-init my-pipeline
    polyris-init my-pipeline --local
    polyris-init my-pipeline --schedule @hourly
"""

import argparse
from typing import Any, List
import sys
from pathlib import Path


# =============================================================================
# Templates
# =============================================================================

LOCAL_PIPELINE = '''"""
{name} pipeline.

Generated by: polyris init --local

Commands (run from this directory):
    polyris-validate              # Validate pipeline
    polyris-validate -v           # Verbose validation
    polyris-output --json         # Generate ASL JSON
    polyris-output --mermaid      # Generate Mermaid diagram
    polyris-output --graph        # Show DAG as ASCII graph

When ready to deploy:
    polyris-deploy --stage dev
  """
from polyris import DAG, task

with DAG(
    dag_id="{name}",
    schedule="{schedule}",
    description="{name} pipeline",
) as dag:

    # Replace ARNs with your real Step Function ARNs when ready to deploy.
    # For now, these placeholder ARNs let you explore the DSL locally.

    @task.sfn(arn="arn:aws:states:us-east-1:123456789012:stateMachine:{name}-extract")
    def extract():
        """Extract data from source."""
        pass

    @task.sfn(
        arn="arn:aws:states:us-east-1:123456789012:stateMachine:{name}-transform",
        retries=2,
    )
    def transform():
        """Transform extracted data."""
        pass

    @task.sfn(
        arn="arn:aws:states:us-east-1:123456789012:stateMachine:{name}-load",
        trigger_rule="all_success",
    )
    def load():
        """Load transformed data to destination."""
        pass

    extract() >> transform() >> load()

'''


CFN_PIPELINE = '''"""
{name} pipeline.

Generated by: polyris init (default — CloudFormation-ready)

Commands (run from this directory):
    polyris-validate              # Validate pipeline
    polyris-validate -v           # Verbose validation
    polyris-output --json         # Generate ASL JSON
    polyris-output --mermaid      # Generate Mermaid diagram
    polyris-output --graph        # Show DAG as ASCII graph

Deploy:
    polyris-deploy --stage dev
  """
from polyris import DAG, task

with DAG(
    dag_id="{name}",
    schedule="{schedule}",
    description="{name} pipeline",
) as dag:

    # Replace these placeholder ARNs with your real Step Function ARNs.

    @task.sfn(arn="arn:aws:states:us-east-1:123456789012:stateMachine:{name}-extract")
    def extract():
        """Extract data from source."""
        pass

    @task.sfn(
        arn="arn:aws:states:us-east-1:123456789012:stateMachine:{name}-transform",
        retries=2,
    )
    def transform():
        """Transform extracted data."""
        pass

    @task.sfn(
        arn="arn:aws:states:us-east-1:123456789012:stateMachine:{name}-load",
        trigger_rule="all_success",
    )
    def load():
        """Load transformed data to destination."""
        pass

    extract() >> transform() >> load()

'''


# =============================================================================
# Init Logic
# =============================================================================

def init_pipeline(name: str, schedule: str = "@daily", base_dir: str = ".", deploy_method: str = "cfn"):
    """Create a new pipeline scaffold."""

    pipeline_dir = Path(base_dir) / name
    name_under = name.replace("-", "_")

    if pipeline_dir.exists():
        print(f"❌ Directory already exists: {pipeline_dir}")
        sys.exit(1)

    pipeline_dir.mkdir(parents=True)

    fmt = dict(name=name, name_under=name_under, schedule=schedule)

    if deploy_method == "local":
        (pipeline_dir / "dag.py").write_text(LOCAL_PIPELINE.format(**fmt))

        print(f"""
✅ Pipeline created: {pipeline_dir}/

Files:
  {pipeline_dir}/dag.py    — Pipeline definition (no AWS needed!)

Try it now:
  cd {pipeline_dir}
  polyris-validate              # Validate pipeline
  polyris-validate -v           # Verbose output
  polyris-output --json         # Full Step Functions JSON
  polyris-output --mermaid      # Generate diagram
  polyris-output --graph        # Show DAG as ASCII graph

Ready to deploy? Re-run without --local to scaffold a deployable pipeline:
  polyris-init {name}
""")
    else:
        # deploy_method == "cfn" (the default per the CLI's own --help/epilog:
        # "polyris-init my-pipeline # Create a pipeline (default)"). This
        # branch previously did not exist at all: the directory was created,
        # zero files were written, and nothing was printed — the tool's own
        # documented default invocation silently did nothing.
        (pipeline_dir / "dag.py").write_text(CFN_PIPELINE.format(**fmt))

        print(f"""
✅ Pipeline created: {pipeline_dir}/

Files:
  {pipeline_dir}/dag.py    — Pipeline definition

Try it now:
  cd {pipeline_dir}
  polyris-validate              # Validate pipeline
  polyris-validate -v           # Verbose output

Deploy:
  polyris-deploy --stage dev
""")


SCHEDULES = {
    "1": ("@daily", "Once per day (midnight UTC)"),
    "2": ("@hourly", "Once per hour"),
    "3": ("@weekly", "Once per week (Sunday midnight)"),
    "4": ("0 9 * * MON-FRI", "Weekdays at 9 AM UTC"),
    "5": ("None", "Manual only (no schedule)"),
}

DEPLOY_METHODS = {
    "1": ("local", "Try locally without AWS (explore DSL)"),
    "2": ("cfn", "CloudFormation — deploy via polyris-deploy"),
}


def _ask(prompt, default=None):
    """Ask user for input with optional default."""
    if default:
        result = input(f"  {prompt} [{default}]: ").strip()
        return result or default
    return input(f"  {prompt}: ").strip()


def _ask_choice(prompt, choices):
    """Ask user to pick from numbered choices."""
    print(f"\n  {prompt}")
    for key, (_, desc) in choices.items():
        print(f"    {key}) {desc}")
    while True:
        choice = input("  Choice [1]: ").strip() or "1"
        if choice in choices:
            return choices[choice][0]
        print(f"  Invalid choice. Pick {', '.join(choices.keys())}.")


def _build_custom_pipeline(name, schedule, tasks, deploy_method, use_remote_state=False):
    """Generate pipeline code from interactive wizard inputs."""
    
    # Build task definitions
    task_defs = []
    task_calls = []
    for t in tasks:
        params = [f'arn="arn:aws:states:us-east-1:123456789012:stateMachine:{name}-{t["name"]}"']
        if t.get("retries"):
            params.append(f'retries={t["retries"]}')
        if t.get("trigger_rule") and t["trigger_rule"] != "all_success":
            params.append(f'trigger_rule="{t["trigger_rule"]}"')
        
        params_str = ", ".join(params)
        func_name = t["name"].replace("-", "_")
        desc = t.get("description", f'{t["name"].replace("-", " ").title()} step.')
        
        task_defs.append(f'''    @task.sfn({params_str})
    def {func_name}():
        """{desc}"""
        pass''')
        task_calls.append(f"    {func_name}()")

    # Build dependency chains
    dep_lines = []
    for i, t in enumerate(tasks):
        if t.get("depends_on"):
            for dep_name in t["depends_on"]:
                dep_func = dep_name.replace("-", "_")
                task_func = t["name"].replace("-", "_")
                dep_lines.append(f"    {dep_func}() >> {task_func}()")
    
    # If no explicit deps, chain sequentially
    if not dep_lines and len(tasks) > 1:
        chain = " >> ".join(t["name"].replace("-", "_") + "()" for t in tasks)
        dep_lines = [f"    {chain}"]

    schedule_str = f'"{schedule}"' if schedule != "None" else "None"
    
    if deploy_method == "local":
        header = f'''"""
{name} pipeline.

Generated by: polyris init -i --local

Commands (run from this directory):
    polyris-validate              # Validate pipeline
    polyris-validate -v           # Verbose validation
    polyris-output --json         # Generate ASL JSON
    polyris-output --mermaid      # Generate Mermaid diagram
    polyris-output --graph        # Show DAG as ASCII graph

When ready to deploy:
    polyris-deploy --stage dev
"""
from polyris import DAG, task'''
        footer = '''
# Deploy: polyris-deploy --stage dev'''
    else:
        if use_remote_state:
            header = f'''"""
{name} pipeline.

Generated by: polyris init -i
"""
import os
from polyris import DAG, task

STAGE = os.environ.get("POLYRIS_STAGE", "dev")'''
            footer = '''
# Deploy: polyris-deploy --stage $STAGE'''
        else:
            header = f'''"""
{name} pipeline.

Generated by: polyris init -i
"""
import os
from polyris import DAG, task

STAGE = os.environ.get("POLYRIS_STAGE", "dev")'''
            footer = '''
# Deploy: polyris-deploy --stage $STAGE'''
    
    code = f'''{header}

with DAG(
    dag_id="{name}",
    schedule={schedule_str},
    description="{name} pipeline",
) as dag:

{chr(10).join(task_defs)}

{chr(10).join(dep_lines)}
{footer}
'''
    return code


def interactive_init(name: str, base_dir: str = "."):
    """Interactive pipeline creation wizard."""
    
    print("""
╔══════════════════════════════════════╗
║     polyris pipeline wizard 🧙      ║
╚══════════════════════════════════════╝
""")
    
    # 1. Deploy method
    deploy_method = _ask_choice("How do you want to run this pipeline?", DEPLOY_METHODS)
    
    # 2. Schedule
    schedule = _ask_choice("Schedule:", SCHEDULES)
    
    # 3. Tasks
    print("\n  Define your tasks (press Enter on an empty name to finish):")
    tasks: List[Any] = []
    task_num = 1
    while True:
        # Only the first task carries a suggestion. It used to be
        # {1: extract, 2: transform, 3: load}, which silently contradicted the
        # line above: _ask() returns `result or default`, so Enter accepted the
        # suggestion instead of finishing and no pipeline under three tasks
        # could be built at all. The scaffold is a nudge for an empty wizard,
        # not a floor on task count.
        task_name = _ask(f"Task {task_num} name", default="extract" if not tasks else None)
        if not task_name:
            break
        
        task_info = {"name": task_name}
        
        # Ask for retries (quick)
        retries = _ask(f"  Retries for '{task_name}'", default="0")
        if retries != "0":
            task_info["retries"] = int(retries)
        
        tasks.append(task_info)
        task_num += 1
    
    # 4. Dependencies
    if len(tasks) > 1:
        print("\n  Dependencies (current: sequential chain)")
        print(f"    Chain: {' → '.join(t['name'] for t in tasks)}")
        keep_chain = _ask("  Keep sequential chain? (y/n)", default="y")
        
        if keep_chain.lower() != "y":
            print("  Define dependencies for each task:")
            task_names = [t["name"] for t in tasks]
            for i, t in enumerate(tasks):
                if i == 0:
                    continue
                available = task_names[:i]
                deps = _ask(f"    '{t['name']}' depends on (comma-separated, or 'none')", 
                           default=",".join(available))
                if deps.lower() != "none":
                    t["depends_on"] = [d.strip() for d in deps.split(",") if d.strip() in task_names]
    
    # 5. Generate
    pipeline_dir = Path(base_dir) / name
    if pipeline_dir.exists():
        print(f"\n❌ Directory already exists: {pipeline_dir}")
        sys.exit(1)
    
    pipeline_dir.mkdir(parents=True)
    
    code = _build_custom_pipeline(name, schedule, tasks, deploy_method)
    
    filename = "dag.py"
    (pipeline_dir / filename).write_text(code)
    
    print(f"\n✅ Pipeline created: {pipeline_dir}/{filename}")
    print(f"   Tasks: {' → '.join(t['name'] for t in tasks)}")
    print(f"   Schedule: {schedule}")
    print(f"   Deploy: {deploy_method}")
    
    if deploy_method == "local":
        print(f"""
Try it now:
  cd {pipeline_dir}
  polyris-validate              # Validate pipeline
  polyris-validate -v           # Verbose output
  polyris-output --json         # Full Step Functions JSON
  polyris-output --mermaid      # Generate diagram
  polyris-output --graph        # Show DAG as ASCII graph
""")
    elif deploy_method == "cfn":
        print(f"""
Next steps:
  cd {pipeline_dir}
  polyris-deploy
""")
    else:  # pragma: no cover -- unreachable via the public API: deploy_method
        # comes only from _ask_choice(DEPLOY_METHODS), which yields local|cfn.
        # Kept as a graceful default so adding a third method degrades to a
        # generic next-steps block instead of printing nothing.
        print(f"""
Next steps:
  cd {pipeline_dir}
  polyris-validate
  polyris-deploy
""")


CONFIG_PY_TEMPLATE = """# Polyris Project Configuration
# ============================================================
# This file configures your polyris project environments.
# Each environment maps to a separate AWS deployment.
#
# Usage:
#   polyris-deploy --stage dev
#   polyris-deploy --stage prod --profile my-aws-profile
# ============================================================

ENVIRONMENTS = {{
    "dev": {{
        "namespace": "{namespace}",
        "stage": "dev",
        "region": "us-east-1",
        # "profile": "my-dev-profile",  # optional AWS profile
        # "roles": {{
        #     "etl": "arn:aws:iam::123456789012:role/etl-role",
        # }},
    }},
    "prod": {{
        "namespace": "{namespace}",
        "stage": "prod",
        "region": "us-east-1",
        # "profile": "my-prod-profile",
        # "roles": {{
        #     "etl": "arn:aws:iam::123456789012:role/etl-role",
        # }},
    }},
}}

# Default stage when --stage is not specified
DEFAULT_STAGE = "dev"
"""


def init_project(base_dir: str = ".") -> None:
    """Generate config.py template in the project root."""
    config_path = Path(base_dir) / "config.py"

    if config_path.exists():
        print(f"❌ config.py already exists: {config_path}")
        sys.exit(1)

    # Ask for namespace
    namespace = input("  Project namespace (e.g. myorg): ").strip()
    if not namespace:
        namespace = "myorg"

    config_path.write_text(CONFIG_PY_TEMPLATE.format(namespace=namespace))
    print(f"""
✅ Project config created: {config_path}

Next steps:
  1. Edit config.py — set your namespace, region, AWS profiles
  2. Create your first pipeline:
       polyris-init my-pipeline
  3. Deploy infrastructure:
       polyris-deploy --stage dev
""")



def main():
    parser = argparse.ArgumentParser(
        prog="polyris-init",
        description="Create a new polyris pipeline",
        epilog="Examples:\n  polyris-init --project                # Initialize project config.py\n  polyris-init my-pipeline              # Create a pipeline (default)\n  polyris-init my-pipeline --local      # Try without AWS\n  polyris-init my-pipeline --schedule @hourly"
    )
    parser.add_argument("name", nargs="?", default=None, help="Pipeline name (e.g. my-pipeline)")

    deploy_group = parser.add_mutually_exclusive_group()
    deploy_group.add_argument("--cfn", action="store_const", dest="deploy", const="cfn", help="Generate CloudFormation-ready files (default)")
    deploy_group.add_argument("--local", action="store_const", dest="deploy", const="local", help="Try locally without AWS (explore DSL)")

    parser.add_argument("--schedule", default=None, help="Cron schedule (default: @daily)")

    parser.add_argument("--dir", default=".", help="Base directory (default: current directory)")
    parser.add_argument("-i", "--interactive", action="store_true", help="Interactive wizard")
    parser.add_argument("--project", action="store_true", help="Initialize a new polyris project (creates config.py)")

    args = parser.parse_args()

    if args.project:
        init_project(base_dir=args.dir)
        return

    if args.interactive:
        name = args.name
        if not name:
            name = input("  Pipeline name: ").strip()
            if not name:
                print("❌ Pipeline name is required.")
                sys.exit(1)
        interactive_init(name=name, base_dir=args.dir)
    else:
        if not args.name:
            parser.error("Pipeline name is required (or use -i for interactive mode)")
        init_pipeline(
            name=args.name,
            deploy_method=args.deploy or "cfn",
            schedule=args.schedule or "@daily",
            base_dir=args.dir,

        )


if __name__ == "__main__":  # pragma: no cover -- entry-point guard; main() is exercised directly
    main()
