"""
sync_enums — generate enum mirrors from polyris/constants.py.

Canonical source: polyris/constants.py defines 8 enum families. This
script reads them via Python imports (NOT regex; safer + handles
inheritance) and writes:

  1. sam/lambdas/_shared/constants.py        (Lambda shared)
  2. sam/lambdas/console_api/constants.py    (Lambda console_api)
  3. sam/lambdas/evaluate_deps/constants.py  (Lambda evaluate_deps; copied from _shared)
  4. ui/src/generated/enums.ts                (Frontend TypeScript)

Why Python-import the source rather than regex-parse: it lets us
inherit existing logic (TaskStatus is an Enum subclass; PipelineStatus
etc. are plain classes; sets like TERMINAL_STATUSES are derived
expressions). Re-doing all that in regex is brittle.

The generated files include a banner saying "DO NOT EDIT — generated"
and the canonical-source SHA so drift checks are tight.

Usage:
  python -m polyris.codegen.sync_enums          # write
  python -m polyris.codegen.sync_enums --check  # exit 1 if would change
"""
from __future__ import annotations

import argparse
import hashlib
import inspect
import sys
from pathlib import Path
from typing import Iterable

from polyris import constants as src


# ─────────────────────────────────────────────────────────────────────────────
# Header / footer helpers
# ─────────────────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parents[2]
CANONICAL_PATH = REPO_ROOT / "polyris" / "constants.py"


def _canonical_sha() -> str:
    return hashlib.sha256(CANONICAL_PATH.read_bytes()).hexdigest()[:16]


def _py_header(target_name: str) -> str:
    return f'''"""
{target_name} — generated from polyris/constants.py by polyris.codegen.sync_enums.

DO NOT EDIT THIS FILE. Run `make generate-enums` (or
`python -m polyris.codegen.sync_enums`) to regenerate.

Canonical source sha (first 16): {_canonical_sha()}
"""
'''


def _ts_header() -> str:
    return f'''/**
 * Generated from polyris/constants.py by polyris.codegen.sync_enums.
 *
 * DO NOT EDIT THIS FILE. Run `make generate-enums` (or
 * `python -m polyris.codegen.sync_enums`) to regenerate.
 *
 * Canonical source sha (first 16): {_canonical_sha()}
 */
'''


# ─────────────────────────────────────────────────────────────────────────────
# Python body renderers
# ─────────────────────────────────────────────────────────────────────────────

def _enum_class_py(name: str, doc: str, members: Iterable[tuple[str, str]]) -> str:
    """Plain Python class (NOT enum.Enum — Lambda code expects bare strings)."""
    lines = [f"class {name}:", f'    """{doc}"""']
    for attr, val in members:
        lines.append(f'    {attr} = {val!r}')
    return "\n".join(lines) + "\n"


def _set_py(name: str, values: Iterable[str]) -> str:
    return f"{name} = {{\n" + "".join(f"    {v!r},\n" for v in values) + "}\n"


def _render_python_body() -> str:
    """Render Lambda-style constants module body."""
    parts: list[str] = []

    # TaskStatus (lowercase string values)
    parts.append(_enum_class_py(
        "TaskStatus",
        "Task execution status values.",
        [(m.name, m.value) for m in src.TaskStatus],
    ))
    parts.append("\n")
    parts.append(_set_py("TASK_TERMINAL_STATUSES", sorted(src.TERMINAL_STATUSES)))
    parts.append(_set_py("TASK_SETTLED_STATUSES", sorted(src.SETTLED_STATUSES)))
    parts.append(_set_py("TASK_SUCCESS_STATUSES", sorted(src.SUCCESS_STATUSES)))
    parts.append(_set_py("TASK_FAILURE_STATUSES", sorted(src.FAILURE_STATUSES)))
    parts.append(_set_py("TASK_ACTIVE_STATUSES", sorted(src.ACTIVE_STATUSES)))
    parts.append(_set_py("TASK_WAITING_STATUSES", sorted(src.WAITING_STATUSES)))
    parts.append(_set_py("TASK_STOPPABLE_STATUSES", sorted(src.STOPPABLE_STATUSES)))
    parts.append("\n")

    # TriggerRule
    parts.append(_enum_class_py(
        "TriggerRule",
        "Trigger rules.",
        [(n, getattr(src.TriggerRule, n))
         for n in vars(src.TriggerRule) if not n.startswith("_")],
    ))
    parts.append("\n")

    # PipelineStatus, ExecutionStatus, BackfillStatus, etc.
    for cls in (src.PipelineStatus, src.ExecutionStatus,
                src.BackfillStatus, src.BackfillCascade,
                src.BackfillUpstream,
                src.BackfillGranularity, src.StalenessStatus,
                src.AssetOperator):
        members = [(n, getattr(cls, n))
                   for n in vars(cls) if not n.startswith("_")]
        parts.append(_enum_class_py(cls.__name__,
                                    cls.__doc__ or cls.__name__,
                                    members))
        parts.append("\n")

    # Sets / helpers
    parts.append(_set_py("EXECUTION_STATUS_CANONICAL",
                         sorted(src.EXECUTION_STATUS_CANONICAL)))
    parts.append(_set_py("BACKFILL_TERMINAL_STATUSES",
                         sorted(src.BACKFILL_TERMINAL_STATUSES)))
    parts.append(_set_py("BACKFILL_ACTIVE_STATUSES",
                         sorted(src.BACKFILL_ACTIVE_STATUSES)))
    parts.append(_set_py("BACKFILL_ERROR_CODES",
                         sorted(src.BACKFILL_ERROR_CODES)))
    parts.append("\n")

    # normalize_execution_status function — verbatim source
    parts.append(_normalize_helper_py())

    # derive_execution_status + reconcile_execution_status — verbatim SDK source
    # (ADR #112). Rendered via inspect so the canonical logic lives in exactly one
    # place (polyris.constants) and the generated copies cannot drift.
    parts.append(_derive_helper_py())

    return "".join(parts)


def _derive_helper_py() -> str:
    """Render the execution-status derivation + reconciliation helpers (ADR #112).

    The status groupings are emitted from the canonical set values; the two
    functions are emitted verbatim from ``polyris.constants`` via ``inspect`` so
    there is a single source of truth for the logic.
    """
    set_lines = "".join(
        f"{name} = {{{', '.join(repr(v) for v in sorted(getattr(src, name)))}}}\n"
        for name in ("_DERIVE_RESOLVED", "_DERIVE_FAILURE", "_DERIVE_STOPPED", "_DERIVE_TERMINAL")
    )
    return (
        "\n"
        + set_lines
        + "\n"
        + inspect.getsource(src.derive_execution_status)
        + "\n"
        + inspect.getsource(src.reconcile_execution_status)
    )


def _normalize_helper_py() -> str:
    """Generate the normalize_execution_status helper as text.

    Kept verbatim across copies to avoid drift; the dict mirrors
    the canonical's UPPERCASE map.
    """
    upper_map = src._EXECUTION_STATUS_UPPERCASE_MAP
    map_items = "".join(f"    {k!r}: {v!r},\n" for k, v in upper_map.items())
    return (
        "_EXECUTION_STATUS_UPPERCASE_MAP = {\n"
        f"{map_items}"
        "}\n\n"
        "def normalize_execution_status(status, log_warn=None):\n"
        '    """Normalize a pipeline-execution status to canonical lowercase.\n'
        "\n"
        "    Generated mirror of polyris.constants.normalize_execution_status.\n"
        '    See ADR #71 for full reasoning. Idempotent on canonical inputs.\n'
        '    """\n'
        "    if status is None:\n"
        "        return None\n"
        "    if status in EXECUTION_STATUS_CANONICAL:\n"
        "        return status\n"
        "    mapped = _EXECUTION_STATUS_UPPERCASE_MAP.get(status)\n"
        "    if mapped is not None:\n"
        "        return mapped\n"
        "    if log_warn is not None:\n"
        '        log_warn("Unexpected execution status; cannot normalize",\n'
        "                 status=status)\n"
        "    return status\n"
    )


# ─────────────────────────────────────────────────────────────────────────────
# TypeScript body renderer
# ─────────────────────────────────────────────────────────────────────────────

def _ts_union(name: str, doc: str, values: Iterable[str]) -> str:
    return (
        f"/** {doc} */\n"
        f"export type {name} =\n  | "
        + "\n  | ".join(f"'{v}'" for v in values)
        + ";\n"
    )


def _ts_array(name: str, doc: str, values: Iterable[str]) -> str:
    return (
        f"/** {doc} */\n"
        f"export const {name}: ReadonlyArray<string> = [\n"
        + "".join(f"    '{v}',\n" for v in values)
        + "];\n"
    )


def _ts_object(name: str, doc: str, members: Iterable[tuple[str, str]]) -> str:
    """Named-key const object mirroring an Enum's members, for ergonomic UI
    value access (e.g. ``TASK_STATUS.SUCCESS``). `as const` keeps literal
    types. Emitted alongside the union type so the UI has a single generated
    source of both the type and the values (ADR #93)."""
    return (
        f"/** {doc} */\n"
        f"export const {name} = {{\n"
        + "".join(f"    {attr}: '{val}',\n" for attr, val in members)
        + "} as const;\n"
    )


def _render_ts_body() -> str:
    parts: list[str] = []

    parts.append(_ts_union(
        "TaskStatus",
        "Task execution status values (canonical lowercase).",
        [m.value for m in src.TaskStatus],
    ))
    parts.append("\n")

    parts.append(_ts_object(
        "TASK_STATUS",
        "Task status values keyed by canonical name (UI value access).",
        [(m.name, m.value) for m in src.TaskStatus],
    ))
    parts.append("\n")

    parts.append(_ts_union(
        "TriggerRule",
        "Trigger rules.",
        [getattr(src.TriggerRule, n) for n in vars(src.TriggerRule)
         if not n.startswith("_")],
    ))
    parts.append("\n")

    for cls in (src.PipelineStatus, src.ExecutionStatus,
                src.BackfillStatus, src.BackfillCascade,
                src.BackfillUpstream,
                src.BackfillGranularity, src.StalenessStatus):
        values = [getattr(cls, n) for n in vars(cls) if not n.startswith("_")]
        parts.append(_ts_union(
            cls.__name__,
            (cls.__doc__ or cls.__name__).strip().split("\n")[0],
            values,
        ))
        parts.append("\n")

    parts.append(_ts_array(
        "BACKFILL_TERMINAL_STATUSES",
        "Backfill statuses that are terminal (no further transitions).",
        sorted(src.BACKFILL_TERMINAL_STATUSES),
    ))
    parts.append("\n")
    parts.append(_ts_array(
        "TASK_TERMINAL_STATUSES",
        "Task statuses that are terminal.",
        sorted(src.TERMINAL_STATUSES),
    ))
    parts.append("\n")
    parts.append(_ts_array(
        "TASK_SETTLED_STATUSES",
        "Task statuses that are 'settled' — terminal, or deliberately stopped "
        "(restartable). A settled task will not change on its own. Single source of "
        "truth for 'is this task done?' checks in the UI.",
        sorted(src.SETTLED_STATUSES),
    ))
    parts.append("\n")
    parts.append(_ts_array(
        "TASK_SUCCESS_STATUSES",
        "Task statuses that count as a successful/resolved outcome "
        "(success, succeeded alias, skipped). Single source of truth for "
        "'done successfully' counts in the UI.",
        sorted(src.SUCCESS_STATUSES),
    ))
    parts.append("\n")
    parts.append(_ts_array(
        "BACKFILL_ERROR_CODES",
        "Backfill error codes the route can return; the UI friendly-error "
        "map must cover every one (ADR #94).",
        sorted(src.BACKFILL_ERROR_CODES),
    ))

    return "".join(parts)


# ─────────────────────────────────────────────────────────────────────────────
# I/O
# ─────────────────────────────────────────────────────────────────────────────

PY_TARGETS = [
    REPO_ROOT / "sam" / "lambdas" / "_shared" / "constants_generated.py",
    REPO_ROOT / "sam" / "lambdas" / "console_api" / "constants_generated.py",
    # v0.79.5 (ADR #77) — evaluate_deps imports the generated module-level
    # status sets (TASK_TERMINAL_STATUSES etc.) from its constants.py copy.
    # The Lambda needs constants_generated.py in its deploy artifact.
    REPO_ROOT / "sam" / "lambdas" / "evaluate_deps" / "constants_generated.py",
]

TS_TARGET = REPO_ROOT / "ui" / "src" / "generated" / "enums.ts"


def _render_py_file(target_name: str) -> bytes:
    return (_py_header(target_name) + "\n" + _render_python_body()).encode("utf-8")


def _render_ts_file() -> bytes:
    return (_ts_header() + "\n" + _render_ts_body()).encode("utf-8")


def write_all() -> dict[Path, bool]:
    """Write all targets. Returns {path: changed}."""
    result: dict[Path, bool] = {}
    for target in PY_TARGETS:
        target.parent.mkdir(parents=True, exist_ok=True)
        body = _render_py_file(target.name)
        existing = target.read_bytes() if target.exists() else b""
        if existing != body:
            target.write_bytes(body)
            result[target] = True
        else:
            result[target] = False

    TS_TARGET.parent.mkdir(parents=True, exist_ok=True)
    ts_body = _render_ts_file()
    existing = TS_TARGET.read_bytes() if TS_TARGET.exists() else b""
    if existing != ts_body:
        TS_TARGET.write_bytes(ts_body)
        result[TS_TARGET] = True
    else:
        result[TS_TARGET] = False

    return result


def check_all() -> dict[Path, bool]:
    """Same as write_all but doesn't write — returns {path: would_change}."""
    result: dict[Path, bool] = {}
    for target in PY_TARGETS:
        body = _render_py_file(target.name)
        existing = target.read_bytes() if target.exists() else b""
        result[target] = (existing != body)
    ts_body = _render_ts_file()
    existing = TS_TARGET.read_bytes() if TS_TARGET.exists() else b""
    result[TS_TARGET] = (existing != ts_body)
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if generated files would change; don't write.")
    args = parser.parse_args()

    if args.check:
        changes = check_all()
        drifted = [str(p) for p, changed in changes.items() if changed]
        if drifted:
            sys.stderr.write(
                "❌ Generated enum files are out of sync with "
                "polyris/constants.py:\n"
            )
            for p in drifted:
                sys.stderr.write(f"   {p}\n")
            sys.stderr.write("Run: python -m polyris.codegen.sync_enums\n")
            return 1
        print("✅ Generated enums in sync")
        return 0

    changes = write_all()
    written = [path for path, changed in changes.items() if changed]
    if written:
        print(f"✅ Wrote {len(written)} file(s):")
        for path in written:
            print(f"   {path.relative_to(REPO_ROOT)}")
    else:
        print("✅ Already in sync, no changes written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
