#!/bin/bash
# deploy.sh — Upload built UI to S3 and invalidate CloudFront cache
#
# Generates config.js with real API Gateway URL and Cognito settings
# from CloudFormation stack outputs, so no env vars needed at build time.
#
# Usage:
#   cd ui
#   ./deploy.sh <stack-name> <region>                       # profile defaults to `default`
#   ./deploy.sh <stack-name> <region> ./out --profile X     # override ui-out and profile
#   ./deploy.sh --stack polyris-dev --region us-east-1 --profile X    # named flags
#
# All values are read from the CLI — the script deliberately does NOT touch
# config.py (that's a pipeline concern, not a UI-deploy concern) or
# sam/samconfig.toml. Whoever calls this passes what it needs; the setup
# script in scripts/setup-polyris.sh does the reading and passes explicit
# args.

set -e
set -o pipefail

STACK_NAME=""
REGION=""
AWS_PROFILE_FLAG=""
positional=()

# Parse args: --stack, --region, --profile may appear ANYWHERE.
# Everything else is positional: stack-name, region, ui-out-dir.
while [ $# -gt 0 ]; do
  case "$1" in
    --stack)     STACK_NAME="${2:-}"; shift 2 2>/dev/null || shift ;;
    --stack=*)   STACK_NAME="${1#*=}"; shift ;;
    --region)    REGION="${2:-}"; shift 2 2>/dev/null || shift ;;
    --region=*)  REGION="${1#*=}"; shift ;;
    --profile)   AWS_PROFILE_FLAG="--profile ${2:-}"; shift 2 2>/dev/null || shift ;;
    --profile=*) AWS_PROFILE_FLAG="--profile ${1#*=}"; shift ;;
    *)           positional+=("$1"); shift ;;
  esac
done

# Named flags win; otherwise fall back to positional (backward compat with the
# original `./deploy.sh stack region ./out --profile X` form).
STACK_NAME="${STACK_NAME:-${positional[0]:-}}"
REGION="${REGION:-${positional[1]:-}}"
UI_OUT_DIR="${positional[2]:-./out}"

if [ -z "$STACK_NAME" ] || [ -z "$REGION" ]; then
  echo "❌ stack-name and region are required." >&2
  echo "   Usage: ./deploy.sh <stack-name> <region> [ui-out-dir] [--profile NAME]" >&2
  exit 1
fi

if [ ! -d "$UI_OUT_DIR" ]; then
  echo "Error: UI build not found at $UI_OUT_DIR"
  echo "Run: cd ../ui && npm ci && npm run build"
  exit 1
fi

# Pre-deploy summary — shown before any AWS call so the operator sees exactly
# where output goes. Kept short: one line per resolved field.
echo ""
echo "── Deploy target ──────────────────────────────────────────────────"
echo "   sam stack:    $STACK_NAME"
echo "   region:       $REGION"
echo "   profile:      ${AWS_PROFILE_FLAG:-(default)}"
echo "   ui build:     $UI_OUT_DIR"
echo "───────────────────────────────────────────────────────────────────"
echo ""

echo "Fetching stack outputs for: $STACK_NAME"

get_output() {
  aws cloudformation describe-stacks $AWS_PROFILE_FLAG \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

UI_BUCKET=$(get_output "ConsoleUiBucket")
DIST_ID=$(get_output "ConsoleUiDistributionId")
CONSOLE_URL=$(get_output "ConsoleUiUrl")
API_URL_RAW=$(get_output "ConsoleApiUrl")
COGNITO_POOL_ID=$(get_output "CognitoUserPoolId")
COGNITO_CLIENT_ID=$(get_output "CognitoClientId")

# Validate every output that we'll bake into config.js or use for
# invalidation. Empty / "None" here means describe-stacks failed silently or
# the stack really isn't polyris (wrong name / wrong region / wrong profile).
# Missing this catches the failure mode where get_output returns "" and the
# script cheerfully writes API_URL: '/api' into config.js.
_require_output() {
  local name="$1" value="$2"
  if [ -z "$value" ] || [ "$value" = "None" ]; then
    echo "❌ CloudFormation output \"$name\" is empty for stack $STACK_NAME." >&2
    echo "   Check: --stack / --region / --profile point at a real polyris stack." >&2
    exit 1
  fi
}

_require_output "ConsoleUiBucket"         "$UI_BUCKET"
_require_output "ConsoleUiDistributionId" "$DIST_ID"
_require_output "ConsoleUiUrl"            "$CONSOLE_URL"
_require_output "ConsoleApiUrl"           "$API_URL_RAW"
API_URL="${API_URL_RAW}/api"

# Generate config.js with real values — loaded at runtime in browser
echo "Generating config.js with stack outputs..."
AUTH_ENABLED="false"
if [ -n "$COGNITO_POOL_ID" ] && [ "$COGNITO_POOL_ID" != "None" ]; then
  AUTH_ENABLED="true"
fi

cat > "$UI_OUT_DIR/config.js" << ENDOFCONFIG
// Polyris Console Configuration
// Auto-generated by ui/deploy.sh — do not edit manually
window.CONFIG = {
    API_URL: '$API_URL',
    POLL_INTERVAL: 30000,
    AUTH: {
        enabled: $AUTH_ENABLED,
        userPoolId: '$COGNITO_POOL_ID',
        clientId: '$COGNITO_CLIENT_ID',
        region: '$REGION'
    }
};
ENDOFCONFIG

echo "Uploading UI to s3://$UI_BUCKET"

# Assets (_next/static) — immutable cache (content-hashed filenames)
aws s3 sync "$UI_OUT_DIR" "s3://$UI_BUCKET" $AWS_PROFILE_FLAG \
  --delete \
  --exclude "*.html" \
  --exclude "config.js" \
  --cache-control "public, max-age=31536000, immutable"

# HTML files — no cache (always fresh)
aws s3 sync "$UI_OUT_DIR" "s3://$UI_BUCKET" $AWS_PROFILE_FLAG \
  --delete \
  --exclude "*" \
  --include "*.html" \
  --cache-control "public, max-age=0, must-revalidate"

# config.js — no cache (contains runtime config)
aws s3 cp "$UI_OUT_DIR/config.js" "s3://$UI_BUCKET/config.js" $AWS_PROFILE_FLAG \
  --cache-control "public, max-age=0, must-revalidate"

echo "Invalidating CloudFront cache: $DIST_ID"
aws cloudfront create-invalidation $AWS_PROFILE_FLAG \
  --distribution-id "$DIST_ID" \
  --paths "/*" \
  --region us-east-1 \
  --output text > /dev/null

echo ""
echo "✅ UI deployed successfully!"
echo "   URL: $CONSOLE_URL"
echo "   API: $API_URL"
